### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by nanosonde** [forty2/bravia2mqtt#1]
Hi!

I am trying this module with a Sony KDL-75W855C.
Is there anything special I have to setup on the TV itself?
Something like "enable remote control via IP"?

I get the following error:

```
root@rpi-smarthome:~#` bravia2mqtt
BraviaTv {
  domain: null,
  _events:
   { 'power-changed': [Function],
     'volume-changed': [Function],
     'mute-changed': [Function],
     'channel-changed': [Function],
     'input-changed': [Function],
     'piture-mute-changed': [Function],
     'pip-changed': [Function] },
  _eventsCount: 7,
  _maxListeners: undefined,
  sendIrCode: [Function],
  isOn: { get: [Function], set: [Function], toggle: [Function] },
  volume: { get: [Function], set: [Function] },
  isMuted: { get: [Function], set: [Function] },
  channel: { get: [Function], set: [Function] },
  tripletChannel: { get: [Function], set: [Function] },
  inputSource: { get: [Function], set: [Function] },
  input: { get: [Function], set: [Function] },
  isPictureMuted: { get: [Function], set: [Function], toggle: [Function] },
  isPipEnabled: { get: [Function], set: [Function], toggle: [Function] },
  pipPosition: { toggle: [Function] },
  broadcastAddress: { get: [Function] },
  macAddress: { get: [Function] },
  sceneSetting: { get: [Function], set: [Function] } }
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 192.168.10.199:20060
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
root@rpi-smarthome:~#

```

**Comment by forty2** [comment]
Hi!

I apologize for the slow response; somehow my notifications got turned off and I had no idea there was a bug waiting for me. That's fixed now so it shouldn't happen again.

Yes, there is a setting. I believe it's under Settings, then Network.  If I remember correctly, it's called "Simple IP Control". It's in the same screen as the pre shared key for UPnP style control. When I get home tonight I can look up the exact location.  I'll also add it to the README -- seems like useful information to put there.

**Comment by forty2** [comment]
The setting can be found in Settings | Network | Home Network | IP Control | Simple IP Control

**Comment by nanosonde** [comment]
It is working now. Thanks!
